### ISSUE TITLE
русификация грамматических деталей

### ISSUE THREAD

**Issue by Devamitta** [Devamitta/exporter#3]
Сейчас словарь имеет в основном английское содержание и лишь одну русскую колонку, которая содержит перевод слов в контексте.
![image](https://user-images.githubusercontent.com/39419221/188421610-b062322d-970d-4e73-b821-36089a8ec5fa.png)
Вся грамматическая информация приводится на английском.
Чтобы полностью русифицировать словарь нужен код для замены грамматических терминов из [abbreviations.csv](https://github.com/Devamitta/exporter/blob/main/assets/abbreviations.csv)
так как основная база будет на английском поэтому нужно чтобы код менял грамматические сокращения на соответствующие русские лишь перед выгрузкой в Golden Dict формат.
Задачи:
- использовать общепринятые сокращения для всех слов имеющих в столбце ru-abbrev.
- создать код, который будет заменять эти сокращения в столбцах [POS]; [Grammar]; [Neg]; [Verb]; [Trans]; [Case]; [Base]

необходимо учитывать что внутри данной [программы](https://github.com/Devamitta/exporter/blob/main/generate_html_and_json.py) содержание столбца  [POS] влияет на создание словаря. см. [ссылку](https://github.com/Devamitta/exporter/blob/d83c3312eef4aa5d985e744dbaefb1bf336fb92a/generate_html_and_json.py#L50)

примеры исходных csv [здесь](https://github.com/Devamitta/exporter/tree/main/examples)

**Comment by bergentroll** [comment]
> - использовать общепринятые сокращения для всех слов имеющих в столбце ru-abbrev символ "√"

Так понял, `abbreviations.csv` содержит все допустимые сокращения. Для каждого сокращения следует заполнить перевод на русский в столбце `ru-abbrev`.  Затем при сборке словаря налету заменять сокращения в перечисленных полях (`POS`, `Grammar`, `Neg`...) на их перевод из столбца `ru-abbrev`.

Уточнение про символ «√» не понял: в столбце `ru-abbrev` нигде его не вижу.

**Comment by Devamitta** [comment]
Все верно.

`символ "√"` было неверно указано - почистил

**Comment by bergentroll** [comment]
В ветке [3-grammar-terms-russification](/Devamitta/exporter/tree/3-grammar-terms-russification) реализовал подстановку сокращений «наивным» алгоритмом:

- У `DpsWord` добавлен метод `translate_abbreviations()`.
- Метод вызывается для каждого слова при сборке DPS.
- Метод использует словарик, где ключ — строка из поля `abbrev` `abbreviations.csv`, а значение — строка из поля `ru-abbrev`.
- Метод перебирает необходимые поля (`pos`, `grammar` ... `base`) и заменяет совпадения с ключом в словарике на соответствующее значение.
- Ключ ищет совпадения от самых длинных (начиная с `in comps`) до самых коротких (заканчивая `ve`). Это предотвращает некорректную замену, например, в строке `abstr` по ключу `abs` вместо  `abstr`.

При запуске с ключом `./exporter.py --log-level debug run-generate-html-and-json` в начале будет выведен словарь замен сокращений. Так же добавлен ключ `--profiling`, с которым выводится служебная информация о времени, затраченном в каждой функции (с этим ключом программа работает дольше).

Будет хорошо, если бханте посмотрит работоспособность. :pray:

Идеи по улучшению алгоритма:
- Вместо замены в строке методом `str.replace()`, разбивать строку на лексемы, включая знаки `+`, `,`. Проверять замены для отдельных лексем. Может несколько повысить точность замен. Может повысить быстродействие.
- Создавать словарь c кэшем замен. Поскольку строки часто повторяются, это должно немного ускорить исполнение.

Сам файл `abbreviations.csv` пока не менял.

**Comment by Devamitta** [comment]
попробовал, замелил следующее:
- не отображается кнопка "склонения\спряжения" которая открывает страницу inflections. Она была завязана на английские сокращения в графе POS. 
https://github.com/Devamitta/exporter/blob/6d9847eaf43e7a672cc68ffe3ae1d3b46925d5de/helpers.py#L25
возможно следует производить замену после выполнения этой операции. Сейчас таблица склонений показывается открытой сразу
![image](https://user-images.githubusercontent.com/39419221/203244674-a78fced7-f9f9-44ef-8ecd-69d572574d50.png)

**Comment by Devamitta** [comment]
и возможно ли производить такую же замену в html inflections? но для этого думаю нужно менять код 
https://github.com/Devamitta/inflection-generator-dps
и нюанс в том что нужно будет создавать английские и русские варианты таблиц склонения. Насколько это реально выполнимо?

**Comment by Devamitta** [comment]
![image](https://user-images.githubusercontent.com/39419221/203254768-fa7dd65d-c542-47ce-8fb6-75fb703c56da.png)
![image](https://user-images.githubusercontent.com/39419221/203255001-2483ce42-bfd3-4ef7-bcc5-49cbfcf95500.png)

перед информацией из столбца [derived from] было `from` а сейчас ничего нет. Думаю будет лучше добавить русский эквивалент `от`

**Comment by bergentroll** [comment]
> * не отображается кнопка "склонения\спряжения" которая открывает страницу inflections. Она была завязана на английские сокращения в графе POS.

На такой случай добавлено поле `DpsWord.pos_orig`. Поправил шаблон.

> перед информацией из столбца [derived from] было from а сейчас ничего нет. Думаю будет лучше добавить русский эквивалент от

Сделал «от» для русского языка и поправил для английского, чтобы не выводилось, если `derived` не указан.

Предложение: выделять «слово-родитель» _курсивом_ или кавычками («» для русского, "" для английского).

**Comment by Devamitta** [comment]
Отлично!

Согласен, что можно выделять «слово-родитель» _курсивом_. И предлог "от" и "from" тогда тоже можно курсивом.

Теперь раз у нас есть русские сокращения, нужно чтобы словарь сокращений был русский. 
Сейчас если кликнуть на каждое английское сокращение, оно покажет описание
![image](https://user-images.githubusercontent.com/39419221/203703714-a918d8db-55a3-46d5-ae5a-1d66bbfd1cc1.png)
а теперь нужно чтобы  кликнув на русские сокращения показывалось описание.
Но только в GoldenDict когда кликаешь на слово с точкой на конце, то он открывает только само слово, без точки. А у нас сокращения с токой. Думаю нужно из abbreviations.csv убрать точки из столбца "ru-abbrev" но когда мы выводим их в описание грамматики то думаю что точки там нужны чтобы было ясно что это сокращение.

**Comment by bergentroll** [comment]
Курсив сделал.

Про клик по слову не сразу разобрался. Видимо, речь касается настройки (по клавише `F4`) «Переводить выбранное слово по двойному щелчку».

Про точку не понял — в [abbreviations.csv](/Devamitta/exporter/blob/3-grammar-terms-russification/assets/abbreviations.csv) сокращения без точек.

По словарю русских сокращений ясно, попробую реализовать. :pray:

**Comment by bergentroll** [comment]
Сделал в [3-grammar-terms-russification](/Devamitta/exporter/tree/3-grammar-terms-russification). Сейчас выглядит так:
![изображение](https://user-images.githubusercontent.com/14995027/204623678-1cc8f351-14fe-48a1-8851-70fb3a37c18f.png)


Может быть не дублировать сокращение в тексте жирным?

**Comment by Devamitta** [comment]
отлично!
Объединил с основной веткой.
думаю можно удалять все временные ветки кроме основной.

Благодарю
