### ISSUE TITLE
Дублируются файлы примеров CSV

### ISSUE THREAD

**Issue by bergentroll** [Devamitta/exporter#6]
В директориях `examples/` и `examples/spreadsheets/` находятся одинаковые файлы `dps-full.csv` и `sbs-pd.csv`. Дубли могли появиться после слияния с веткой, в которой CSV-файлы перенесены в поддиректорию `spreadsheets/`.

Когда файлы примеров находятся по пути  `examples/spreadsheets/`, можно запустить скрипт так:
```
export DPS_DIR=examples/
./exporter.py run-generate-html-and-json && ./exporter.py run-generate-goldendict
```

Предложение: удалить файлы `examples/*.csv`.

**Comment by Devamitta** [comment]
done, thanks
